/*
Mouner Dabjan
October 16 2018
Give users motivational quotes 
 */

/**
 *
 * @author modab5310
 */
public class PositivePractive extends javax.swing.JFrame {

    /**
     * Creates new form PositivePractive
     */
    public PositivePractive() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        quotebutton = new javax.swing.JButton();
        motivquote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setText("Postive Practice!");

        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (2).jpg"))); // NOI18N

        instruction.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        instruction.setText("Click on \"Generate Quote\" in order to be motiviated  ");

        quotebutton.setText("Generate Quote");
        quotebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quotebuttonActionPerformed(evt);
            }
        });

        motivquote.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        motivquote.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(picture))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(instruction))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(quotebutton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(motivquote, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(picture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruction)
                .addGap(18, 18, 18)
                .addComponent(quotebutton)
                .addGap(18, 18, 18)
                .addComponent(motivquote, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quotebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quotebuttonActionPerformed

        int Quote; 
        
        Quote = (int)Math.round(Math.random()*7+1); 
        
        // switch case statements
        
        switch (Quote) { 
            case 1:
                motivquote.setText("The Way Get Started Is To Quit Talking And Begin Doing.");
                break;
            case 2:
                motivquote.setText("Don’t Let Yesterday Take Up Too Much Of Today.");
                break;
            case 3:
                motivquote.setText("We May Encounter Many Defeats But We Must Not Be Defeated.");
                break;
            case 4:
                motivquote.setText("We Generate Fears While We Sit. We Overcome Them By Action.");
                break;
            case 5:
                motivquote.setText("Whether You Think You Can Or Think You Can’t, You’re Right.");
                break;
            case 6:
                motivquote.setText("Do What You Can With All You Have, Wherever You Are.");
                break;
            case 7:
                motivquote.setText("To See What Is Right And Not Do It Is A Lack Of Courage.");
                break;
            case 8:
                motivquote.setText("Reading Is To The Mind, As Exercise Is To The Body.");
                break;      
        }   
    }//GEN-LAST:event_quotebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PositivePractive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PositivePractive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PositivePractive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PositivePractive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PositivePractive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instruction;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel motivquote;
    private javax.swing.JLabel picture;
    private javax.swing.JButton quotebutton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
